# 设备配置
DEVICE: "cpu"  # "cuda" 或 "cpu"

# 模型配置 - 使用SMP库的UNet++
MODEL:
  NAME: "UnetPlusPlus"  # SMP支持的模型
  ENCODER_NAME: "resnet34"  # 编码器骨干网络: resnet34, efficientnet-b0, etc.
  ENCODER_WEIGHTS: "imagenet"  # 预训练权重
  IN_CHANNELS: 3  # 输入通道数
  CLASSES: 1  # 输出类别数（水印分割为二分类）
  ACTIVATION: null  # 激活函数，null表示不使用

# 数据配置
DATA:
  ROOT_DIR: "./data/train"
  ADDITIONAL_ROOT_DIRS: []
  IMG_SIZE: 512
  GENERATE_MASK_THRESHOLD: 15  # 降低阈值，提高透明水印检测敏感度
  TRAIN_RATIO: 0.8
  VAL_RATIO: 0.2
  SHUFFLE: True
  # 数据增强策略: "basic", "enhanced", "transparent_watermark"
  # transparent_watermark: 专门针对透明水印优化的增强策略，包含更强的亮度对比度变化、噪声模拟等
  # enhanced: 增强版数据增强，适用于一般水印检测
  # basic: 基础数据增强策略
  AUGMENTATION_TYPE: "transparent_watermark"
  SEED: 42
  NUM_WORKERS: 8
  CACHE_IMAGES: true
  PREFETCH_FACTOR: 4

# 训练配置
TRAIN:
  BATCH_SIZE: 8  # 适当减小批次大小，提高训练稳定性
  EPOCHS: 50     # 增加训练轮数
  LR: 0.00005
  WEIGHT_DECAY: 0.0001
  OUTPUT_DIR: "logs/output"
  MODEL_SAVE_PATH: "models/unet_watermark.pth"
  LOG_INTERVAL: 20
  SAVE_INTERVAL: 10
  USE_EARLY_STOPPING: True  # 禁用早停
  EARLY_STOPPING_PATIENCE: 10  # 如果启用早停，增加耐心值
  USE_AMP: true
  GRADIENT_CLIP: 1.0

# 损失函数配置
LOSS:
  NAME: "DiceLoss"  # 或 "CombinedLoss" 用于组合损失
  MODE: "binary"
  SMOOTH: 1e-5
  BCE_WEIGHT: 0.4      # BCE损失权重
  DICE_WEIGHT: 0.6     # Dice损失权重（新增）
  DICE_SMOOTH: 1e-5    # Dice损失平滑项
  FOCAL_ALPHA: 0.25    # Focal Loss参数（可选）
  FOCAL_GAMMA: 2.0     # Focal Loss参数（可选）

# 优化器配置
OPTIMIZER:
  NAME: "Adam"  # 优化器名称
  LR_SCHEDULER: "ReduceLROnPlateau"  # 学习率调度器
  SCHEDULER_PATIENCE: 5  # 调度器耐心值
  SCHEDULER_FACTOR: 0.5  # 学习率衰减因子

# 预测配置
PREDICT:
  INPUT_PATH: "data/input"  # 输入图像目录
  OUTPUT_DIR: "data/output"  # 输出掩码目录
  BATCH_SIZE: 8  # 批处理大小
  THRESHOLD: 0.5  # 二值化阈值
  POST_PROCESS: true  # 是否应用后处理

# 验证配置
VAL:
  METRICS: ["dice", "iou", "accuracy"]  # 验证指标