# 专门针对文字水印优化的UNet配置
# 设备配置
DEVICE: "cpu"  # "cuda" 或 "cpu"

# 模型配置 - 针对文字水印优化
MODEL:
  NAME: "UnetPlusPlus"  # UNet++对细节处理更好，适合文字
  ENCODER_NAME: "efficientnet-b3"  # 使用更强的编码器提取文字特征
  ENCODER_WEIGHTS: "imagenet"  # 预训练权重
  ENCODER_DEPTH: 5  # 编码器深度
  DECODER_CHANNELS: [256, 128, 64, 32, 16]  # 解码器通道数
  IN_CHANNELS: 3  # 输入通道数
  CLASSES: 1  # 输出类别数（水印分割为二分类）
  ACTIVATION: null  # 激活函数

# 数据配置 - 针对文字水印优化
DATA:
  ROOT_DIR: "./data/train"
  ADDITIONAL_ROOT_DIRS: []
  IMG_SIZE: 512  # 保持较高分辨率以保留文字细节
  GENERATE_MASK_THRESHOLD: 10  # 降低阈值，提高文字检测敏感度
  TRAIN_RATIO: 0.8
  VAL_RATIO: 0.2
  SHUFFLE: True
  # 专门针对文字水印的数据增强策略
  AUGMENTATION_TYPE: "text_watermark"
  SEED: 42
  NUM_WORKERS: 8
  CACHE_IMAGES: true
  PREFETCH_FACTOR: 4
  # 文字水印特定参数
  TEXT_ENHANCEMENT: true  # 启用文字特征增强
  EDGE_ENHANCEMENT: true  # 启用边缘增强
  CONTRAST_BOOST: 1.3     # 对比度增强倍数

# 训练配置 - 针对文字水印优化
TRAIN:
  BATCH_SIZE: 6  # 适当减小批次大小，提高训练稳定性
  EPOCHS: 1500   # 增加训练轮数，文字特征需要更多训练
  LR: 0.003      # 降低学习率，更精细地学习文字特征
  WEIGHT_DECAY: 0.0001
  OUTPUT_DIR: "logs/text_watermark_output"
  MODEL_SAVE_PATH: "models/unet_text_watermark.pth"
  LOG_INTERVAL: 15
  SAVE_INTERVAL: 8
  USE_EARLY_STOPPING: True
  EARLY_STOPPING_PATIENCE: 15  # 增加耐心值，文字特征学习需要更多时间
  USE_AMP: true
  GRADIENT_CLIP: 0.8  # 降低梯度裁剪，保持训练稳定性

# 损失函数配置 - 针对文字水印优化
LOSS:
  NAME: "CombinedLoss"  # 使用组合损失
  MODE: "binary"
  SMOOTH: 1e-6
  BCE_WEIGHT: 0.3      # 降低BCE权重
  DICE_WEIGHT: 0.5     # 增加Dice权重，更关注重叠度
  FOCAL_WEIGHT: 0.2    # 添加Focal Loss，处理难样本
  DICE_SMOOTH: 1e-6
  FOCAL_ALPHA: 0.25    # Focal Loss参数
  FOCAL_GAMMA: 2.5     # 增加gamma，更关注困难样本
  # 文字特定损失参数
  EDGE_LOSS_WEIGHT: 0.1  # 边缘损失权重
  CONNECTIVITY_LOSS_WEIGHT: 0.05  # 连通性损失权重

# 优化器配置
OPTIMIZER:
  NAME: "AdamW"  # 使用AdamW优化器，更好的正则化
  LR_SCHEDULER: "CosineAnnealingWarmRestarts"  # 余弦退火调度器
  SCHEDULER_T_0: 50      # 初始重启周期
  SCHEDULER_T_MULT: 2    # 周期倍增因子
  SCHEDULER_ETA_MIN: 1e-6  # 最小学习率

# 预测配置 - 针对文字水印优化
PREDICT:
  INPUT_PATH: "data/input"
  OUTPUT_DIR: "data/output"
  BATCH_SIZE: 4  # 降低批处理大小，提高预测质量
  THRESHOLD: 0.4  # 降低阈值，提高文字检测敏感度
  POST_PROCESS: true
  # 文字水印特定预测参数
  TEXT_MODE: true           # 启用文字模式
  MULTI_SCALE_TEST: true    # 多尺度测试
  TEST_SCALES: [0.8, 1.0, 1.2]  # 测试尺度
  EDGE_REFINEMENT: true     # 边缘细化
  CONNECTIVITY_CHECK: true  # 连通性检查

# 验证配置
VAL:
  METRICS: ["dice", "iou", "accuracy", "precision", "recall", "f1"]  # 增加更多指标
  # 文字特定验证参数
  TEXT_METRICS: true        # 启用文字特定指标
  CHAR_LEVEL_EVAL: true     # 字符级别评估
  EDGE_ACCURACY: true       # 边缘准确度评估

# 文字水印特定配置
TEXT_WATERMARK:
  # 文字检测参数
  MIN_TEXT_AREA: 50         # 最小文字区域面积
  MAX_TEXT_AREA: 10000      # 最大文字区域面积
  TEXT_ASPECT_RATIO_MIN: 0.2  # 文字长宽比最小值
  TEXT_ASPECT_RATIO_MAX: 10   # 文字长宽比最大值
  
  # 形态学操作参数
  MORPH_KERNEL_SIZE: 3      # 形态学核大小
  DILATE_ITERATIONS: 1      # 膨胀迭代次数
  ERODE_ITERATIONS: 1       # 腐蚀迭代次数
  
  # 连通性参数
  CONNECTIVITY: 8           # 连通性（4或8）
  MIN_COMPONENT_AREA: 30    # 最小连通组件面积
  
  # 文字增强参数
  CLAHE_CLIP_LIMIT: 2.5     # CLAHE对比度限制
  CLAHE_TILE_SIZE: 8        # CLAHE瓦片大小
  CANNY_LOW_THRESHOLD: 40   # Canny边缘检测低阈值
  CANNY_HIGH_THRESHOLD: 120 # Canny边缘检测高阈值
  SHARPEN_STRENGTH: 1.2     # 锐化强度