# 设备配置
DEVICE: "cpu"  # "cuda" 或 "cpu"

# 模型配置 - 使用SMP库的UNet++
MODEL:
  NAME: "UnetPlusPlus"  # SMP支持的模型
  ENCODER_NAME: "resnet34"  # 编码器骨干网络: resnet34, efficientnet-b0, etc.
  ENCODER_WEIGHTS: "imagenet"  # 预训练权重
  IN_CHANNELS: 3  # 输入通道数
  CLASSES: 1  # 输出类别数（水印分割为二分类）
  ACTIVATION: null  # 激活函数，null表示不使用

# 数据配置
DATA:
  ROOT_DIR: "./data/train"
  ADDITIONAL_ROOT_DIRS: []
  IMG_SIZE: 512
  GENERATE_MASK_THRESHOLD: 30
  TRAIN_RATIO: 0.8
  VAL_RATIO: 0.2
  SHUFFLE: True
  SEED: 42
  NUM_WORKERS: 4

# 训练配置
TRAIN:
  BATCH_SIZE: 16  # 批次大小
  EPOCHS: 50  # 训练轮数
  LR: 0.0001  # 初始学习率
  WEIGHT_DECAY: 0.0001  # 权重衰减
  OUTPUT_DIR: "logs/output"  # 输出目录
  MODEL_SAVE_PATH: "models/unet_watermark.pth"  # 模型保存路径
  LOG_INTERVAL: 10  # 日志打印间隔
  SAVE_INTERVAL: 5  # 模型保存间隔
  EARLY_STOPPING_PATIENCE: 10  # 早停耐心值

# 损失函数配置
LOSS:
  NAME: "DiceLoss"  # 损失函数名称: DiceLoss, JaccardLoss, etc.
  MODE: "binary"  # 损失函数模式
  SMOOTH: 1e-5  # 损失函数平滑项
  BCE_WEIGHT: 0.5  # BCE损失权重（如果使用组合损失）
  DICE_SMOOTH: 1e-5  # Dice损失平滑项（向后兼容）

# 优化器配置
OPTIMIZER:
  NAME: "Adam"  # 优化器名称
  LR_SCHEDULER: "ReduceLROnPlateau"  # 学习率调度器
  SCHEDULER_PATIENCE: 5  # 调度器耐心值
  SCHEDULER_FACTOR: 0.5  # 学习率衰减因子

# 预测配置
PREDICT:
  INPUT_PATH: "data/input"  # 输入图像目录
  OUTPUT_DIR: "data/output"  # 输出掩码目录
  BATCH_SIZE: 8  # 批处理大小
  THRESHOLD: 0.5  # 二值化阈值
  POST_PROCESS: true  # 是否应用后处理

# 验证配置
VAL:
  METRICS: ["dice", "iou", "accuracy"]  # 验证指标